### ISSUE TITLE
Any intention to pubblish this app on f-droid?

### ISSUE THREAD

**Issue by darhma** [marcolettieri/proximitycallfix#2]
F-droid.org è un repository di software opensource per android. Ho scoperto questa app su IzzyOnDroid f-droid repo (un repository semi-ufficiale di f-droid) mi domandavo se tu avessi intenzione di pubblicare l'app nel repository ufficiale. Se serve posso provare ad informarmi come fare la richiesta.

F-droid.org is a repository of opensource software for android. I discovered this app on IzzyOnDroid f-droid repo (a semi-official repository of f-droid) I was wondering if you had any intention to publish the app on the official repository. If needed I can try to inquire how to make the request.

**Comment by marcolettieri** [comment]
i've already posted on F-droid. thanks
