### ISSUE TITLE
attach APK to releases?

### ISSUE THREAD

**Issue by IzzySoft** [marcolettieri/proximitycallfix#4]
Currently, you maintain the APK file inside the repository. Wouldn't it be better to attach it to its corresponding release? This has multiple advantages:

* it's the first place people look for it (as it's where most projects have it)
* it would not "bloat" the repo itself (less data to transfer/maintain on forks/clones)

Further, it seems you forgot to increase `versionCode` when replacing the APK today (my updater complained) – which means it won't be offered as update to those having the previous version installed, as Android would consider it the same version.

Thanks for considering!

**Comment by marcolettieri** [comment]
https://github.com/marcolettieri/proximitycallfix/blob/master/app/release/app-release.apk

My bad, just noticed the versionCode not changed. Apk is in app/release

**Comment by IzzySoft** [comment]
Thanks! A little misunderstanding due to my omission of the link: I meant the [releases here](https://github.com/marcolettieri/proximitycallfix/releases) :eyes:

**Comment by IzzySoft** [comment]
As my updater again pulled the file with not-changed versionCode, I'm setting it to Static now. Instead of daily, it hence will only check monthly. Please let me know here when the issue is solved, so I can revert that. Thanks!

**Comment by marcolettieri** [comment]
https://github.com/marcolettieri/proximitycallfix/releases/tag/1.0.1
done

**Comment by IzzySoft** [comment]
Thanks! This works wonderfully. I've just updated metadata here (to pull from your releases) and manually triggered my updater – which fetched and integrated it without complaints :smiley: :tada:

**Comment by marcolettieri** [comment]
Why on your repo there  is this warning? 
NonFreeNet: This application promotes or entirely depends a non-Free network service.

The app don't have access to internet or non free network.
Does you consider the call as non-free network service?
I've submitted a new release, please check the update works correctly on your side

**Comment by IzzySoft** [comment]
> NonFreeNet: This application promotes or entirely depends a non-Free network service.

Scroll down to the library section, watch out for the Ⓝ – you're using Google Play Core. That library automatically triggers NonFreeNet.

> The app don't have access to internet or non free network.

Which cross-checking the app's permissions confirms, yes. Still working on a solution to define exceptions (i.e. override library-triggered AntiFeatures per library) – but I'm only a single player, so that will take a little. Be welcome to nag me once per quarter – or open an issue against https://gitlab.com/IzzyOnDroid/repo so I have a permanent reminder.

> I've submitted a new release, please check the update works correctly on your side

Thanks! Yes, it's pulled fine and accepted (just triggered the updater manually to confirm). Only thing you probably forgot this time is to update `versionName`, which still shows `1.0.1` :wink:

**Comment by IzzySoft** [comment]
**Update:** `NonFreeNet` will be gone for your app with the next sync tomorrow. Implemented an exception to ignore/suppress that AntiFeature if the app doesn't request the `INTERNET` permission.

Thanks for the heads-up, that was overdue.
