### ISSUE TITLE
The newly installed app does not ask for any permission

### ISSUE THREAD

**Issue by darhma** [marcolettieri/proximitycallfix#7]
Device: xiaomi redmi note 7 (lavender)
Android version: lineageos 18.1 (android 11)
App version: 1.0.7 from f-droid

I just reinstalled the app because I had been experiencing the fingerprint screen unlock issue again (#3) and realized that f-droid had not updated to 1.0.7 because a reinstall was required. 

Once I reinstalled the app, pressing the button for requesting permissions tells me that they have already been granted, but that's not really the case: the app doesn't have phone permissions, nor device administrator permissions, nor accessibility permissions.

However, the app is active in the background.

I manually gave the phone and accessibility permissions (which should solve the fingerprint unlocking problem) but I haven't had a chance to test the app yet.

The report is only about not asking for permissions and saying they were granted even when in fact they were not. 

Also, I wanted to ask if it is correct to grant permission for phone and accessibility for the app to work properly. 

Thanks

**Comment by marcolettieri** [comment]
On reinstall permission must be granted again.
Tap retry when the pop-up say permission already granted
Il 23 ago 2021, 23:50 +0200, Dario Martines ***@***.***>, ha scritto:

**Comment by darhma** [comment]
Ok, I hadn't noticed the retry button. In any case, the message that appears (permissions already granted) is a bit misleading because it says that the permissions have been granted, although in reality it is not so. 

It's not a big problem and actually tapping the retry button asks to grant the various permissions, but maybe it would be better to reword the initial message.

Anyway, I solved the permissions issue and fingerprint unlocking now works fine. So I leave to you the decision whether to close the issue or to keep it open until the eventual rewording of the initial message.

Thanks
